Added top level restore method
Necessary to complete the Object API by adding the `#restore` method to compliment the existing `#stub!` method. By default, this method always return `false` because there is nothing to restore unless previously stubbed. This is especially useful when a container is stubbed -- for testing purposes -- but can't be restored because stubbing failed. For example, this previously confusing error will no longer occur: _NoMethodError: undefined method `restore' for module Sod::Container_.

Milestone: minor